libretro: Allow frontends to call disk_set_eject_state with no disk attached
libretro/dosbox-svn pull request #71
Opened 2021-04-07 10:04 UTC by obbardc

Some frontends (e.g. Retro-GTK) try to unmount a disk before setting the
path for a new disk; let's be extra careful in the emulator and check if
a disk really exists before attempting to unmount it.

Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>

2021-04-07 20:58 UTC, realnc requested changes

2021-04-07 20:58 UTC, realnc commented on libretro/libretro.cpp
> +    std::string extension;
You can delete this declaration and move it to the spot where you initialize the extension ...

2021-04-07 20:58 UTC, realnc commented on libretro/libretro.cpp
> +    extension = strrchr(path, '.');
... which is here. So `std::string extension = strrchr(path, '.');`

2021-04-07 20:58 UTC, realnc commented on libretro/libretro.cpp
> +    std::string extension;
Same here.

2021-04-08 07:22 UTC, obbardc commented on libretro/libretro.cpp
> +    std::string extension;
sure; done

2021-04-08 18:52 UTC, realnc approved these changes

2021-04-08 18:53 UTC, merged

2021-04-08 18:54 UTC, realnc commented
Thanks!